---
- name: "Create a host with Satellite into Libvirt"
  hosts: "{{ SAT_NAME }}"
  gather_facts: yes
  tasks:

    - name: "Provisioning a host with provisioning callback"
      redhat.satellite.host:
        username: "{{ SAT_USER }}"
        password: "{{ SAT_PASS }}"
        server_url: "{{ SAT_URL }}"
        organization: "{{ ORG_NAME }}"
        location: "{{ LOCAL_NAME }}"
        hostgroup: "{{ HG_NAME }}"
        name: "{{ HOST_NAME }}.example.local"
        compute_attributes:
          start: "1"
        interfaces_attributes:
        - type: "interface"
          subnet: "PROVISIONING"
          domain: "example.local"
          managed: true
          primary: true
          provision: true
          virtual: false
        - type: "interface"
          subnet: "LOCAL"
          domain: "example.local"
          ip: "192.168.1.{{ HOST_IP }}"
          managed: true
          primary: false
          provision: false
          virtual: false
        build: true
        enabled: true
        managed: true
        state: present
...