---
- hosts: "{{ SAT_NAME }}"
  gather_facts: yes
  tasks:

    - name: "Create an activation key for RHEL 9 base servers"
      redhat.satellite.activation_key:
        username: "admin"
        password: "admin"
        server_url: "{{ SAT_URL }}"
        name: "{{ AK_NAME }}"
        organization: "{{ ORG_NAME }}"
        lifecycle_environment: "{{ LE_NAME }}"
        content_view: "{{ CV_NAME }}"
        host_collections:
            - "{{ HC_NAME }}"
        subscriptions:
          - name: "{{ SUB_NAME }}"
        content_overrides:
            - label: ansible-automation-platform-2.3-for-rhel-9-x86_64-rpms
              override: enabled
            - label: rhel-9-for-x86_64-appstream-rpms
              override: enabled
            - label: rhel-9-for-x86_64-baseos-rpms
              override: enabled
            - label: rhel-9-for-x86_64-supplementary-rpms
              override: enabled
            - label: satellite-client-6-for-rhel-9-x86_64-rpms
              override: enabled
        auto_attach: True
        release_version: "{{ REL_NAME }}"
        service_level: "{{ SL_NAME }}"
...
