---
- hosts: "{{ SAT_NAME }}"
  gather_facts: yes
  tasks:

    - name: "Create an Architecture"
      redhat.satellite.architecture:
        name: "{{ OS_ARCH }}"
        server_url: "{{ SAT_URL }}"
        username: "{{ SAT_USER }}"
        password: "{{ SAT_PASS }}"
        state: absent
...
