---
- name: "Show Satellite variables"
  hosts: all
  tasks:

  - name: "Show Errata Counts"
    debug:
      msg: >
        Bug fixes: {{ foreman.content_attributes.errata_counts.bugfix }},
        Security: {{ foreman.content_attributes.errata_counts.security }},
        Enhancement: {{ foreman.content_attributes.errata_counts.enhancement }},
        Total: {{ foreman.content_attributes.errata_counts.total }}
