---
- hosts: localhost
  collections:
     - community.general
  tasks:

   - name: "Send failing notification message via Slack"
     community.general.slack:
       token: "{{ SLACK_TOKEN }}"
       channel: "{{ SLACK_CHANNEL }}"
       blocks:
         - type: section
           text:
             type: mrkdwn
             text: |-
               *Satellite Host Provisioning:*
               Your requested host was not provisioned successfully. Below you will find all the necessary information about how you can request help. Thank you for using our services!
         - type: context
           elements:
           - type: mrkdwn
             text: |
               Send an email to the address below asking to check the failed deployment.
               *Support Email:* alexon@redhat.com
       msg: "Status: Failed"
       color: '#a11313'
     delegate_to: localhost
...