---
- hosts: localhost
  collections:
     - community.general
  tasks:

   - name: "Send success notification message via Slack"
     community.general.slack:
       token: "{{ SLACK_TOKEN }}"
       channel: "{{ SLACK_CHANNEL }}"
       blocks:
         - type: section
           text:
             type: mrkdwn
             text: |-
               *Satellite Host Provisioning:*
               Your requested host was provisioned successfully. Below you will find all the necessary information about your host and how to access it. Thank you for using our services!
         - type: context
           elements:
           - type: mrkdwn
             text: |
               *Hostname:* {{ HOST_NAME}}.example.local
               *IP Address:* 192.168.1.{{ HOST_IP }}
               *User:* localuser
               *Password:* 123456
       msg: "Status: Success"
       color: '#338cc7'
     delegate_to: localhost
...